name: rebooter # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: reboot pr21
description: |
  reboot pr21

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  rebooter: 
    command: main.py
    plugs:
      - network-bind 
    daemon: simple
    restart-condition: always

parts:
  rebooter:
    plugin: python
    source: .
    python-version: python3
    python-packages: 
    - paramiko
    
  code:
    source: .
    plugin: dump

